import {
  MODEL_GEMINI_NANO,
  MODEL_GEMMA_4_31B_IT,
  MODEL_GEMMA_4_26B_A4B_IT,
  MODEL_GEMINI_3_6_FLASH,
  MODEL_GEMINI_3_5_FLASH,
  MODEL_GEMINI_3_5_FLASH_LITE,
  MODEL_GEMINI_3_1_FLASH_LITE,
  MODEL_GEMINI_3_1_PRO_PREVIEW,
  MODEL_GEMINI_3_1_FLASH_LITE_PREVIEW,
  MODEL_GEMINI_3_PRO_PREVIEW,
  MODEL_GEMINI_3_FLASH_PREVIEW,
  MODEL_GEMINI_2_5_FLASH_LITE,
  MODEL_GEMINI_2_5_FLASH,
  MODEL_GEMINI_2_5_FLASH_LITE_PREVIEW_06_17,
  MODEL_GEMINI_2_5_PRO,
} from '@aituber-onair/core';

// Gemini models list
export const geminiModels = [
  MODEL_GEMINI_3_1_FLASH_LITE,
  MODEL_GEMINI_3_6_FLASH,
  MODEL_GEMINI_3_5_FLASH,
  MODEL_GEMINI_3_5_FLASH_LITE,
  MODEL_GEMINI_3_1_PRO_PREVIEW,
  MODEL_GEMINI_3_FLASH_PREVIEW,
  MODEL_GEMINI_2_5_PRO,
  MODEL_GEMINI_2_5_FLASH,
  MODEL_GEMINI_2_5_FLASH_LITE,
  MODEL_GEMMA_4_31B_IT,
  MODEL_GEMMA_4_26B_A4B_IT,
  MODEL_GEMINI_3_1_FLASH_LITE_PREVIEW,
  MODEL_GEMINI_3_PRO_PREVIEW,
  MODEL_GEMINI_2_5_FLASH_LITE_PREVIEW_06_17,
];

export const geminiNanoModels = [MODEL_GEMINI_NANO];
