import {
  MODEL_GPT_5_NANO,
  MODEL_GPT_5_MINI,
  MODEL_GPT_5,
  MODEL_GPT_5_1,
  MODEL_GPT_5_4,
  MODEL_GPT_5_5,
  MODEL_GPT_5_6,
  MODEL_GPT_5_6_SOL,
  MODEL_GPT_5_6_TERRA,
  MODEL_GPT_5_6_LUNA,
  MODEL_GPT_5_4_MINI,
  MODEL_GPT_5_4_NANO,
  MODEL_GPT_5_4_PRO,
  MODEL_GPT_4_1_NANO,
  MODEL_GPT_4_1_MINI,
  MODEL_GPT_4_1,
  MODEL_O3_MINI,
  MODEL_GPT_4O_MINI,
  MODEL_GPT_4O,
} from '@aituber-onair/core';

// OpenAI models list
export const openaiModels = [
  MODEL_GPT_4_1_NANO,
  MODEL_GPT_4_1_MINI,
  MODEL_GPT_4_1,
  MODEL_GPT_5_NANO,
  MODEL_GPT_5_MINI,
  MODEL_GPT_5,
  MODEL_GPT_5_1,
  MODEL_GPT_5_4,
  MODEL_GPT_5_5,
  MODEL_GPT_5_6,
  MODEL_GPT_5_6_SOL,
  MODEL_GPT_5_6_TERRA,
  MODEL_GPT_5_6_LUNA,
  MODEL_GPT_5_4_MINI,
  MODEL_GPT_5_4_NANO,
  MODEL_GPT_5_4_PRO,
  MODEL_O3_MINI,
  MODEL_GPT_4O_MINI,
  MODEL_GPT_4O,
];

// OpenAI default settings
export const DEFAULT_CHAT_PROVIDER = 'openai';
export const DEFAULT_MODEL = MODEL_GPT_4_1_NANO;
export const DEFAULT_SYSTEM_PROMPT =
  'あなたはフレンドリーなAITuberです。回答はできるだけ一言で、短く自然に返してください。';
