import {
  MODEL_GROK_4_5,
  MODEL_GROK_4_3,
  MODEL_GROK_4_20_REASONING,
  MODEL_GROK_4_20_NON_REASONING,
  MODEL_GROK_4_1_FAST_REASONING,
  MODEL_GROK_4_1_FAST_NON_REASONING,
} from '@aituber-onair/core';

export const xaiModels = [
  MODEL_GROK_4_5,
  MODEL_GROK_4_3,
  MODEL_GROK_4_1_FAST_NON_REASONING,
  MODEL_GROK_4_1_FAST_REASONING,
  MODEL_GROK_4_20_NON_REASONING,
  MODEL_GROK_4_20_REASONING,
];
