import type { FixtureComment } from './types.js';

const BASE_TIME = Date.UTC(2026, 6, 31, 10, 0, 0);

export const STREAM_TITLE = '朝の制作配信｜新しい待機画面をつくる';

export const COMMENTS: readonly FixtureComment[] = [
  {
    id: 'c01',
    platform: 'youtube',
    text: 'おはよう！今日も楽しみにしてます',
    timestamp: BASE_TIME + 6_000,
    atSeconds: 6,
    author: { id: 'u01', name: 'あおい' },
    labels: ['対応不要'],
    attention: '通常',
  },
  {
    id: 'c02',
    platform: 'youtube',
    text: 'その待機画面は何のソフトで作っていますか？',
    timestamp: BASE_TIME + 14_000,
    atSeconds: 14,
    author: { id: 'u02', name: 'Kento' },
    labels: ['質問', '返信候補'],
    attention: '優先',
  },
  {
    id: 'c03',
    platform: 'twitch',
    text: 'BGMが声より少し大きいかもしれません',
    timestamp: BASE_TIME + 22_000,
    atSeconds: 22,
    author: { id: 'u03', name: 'mii' },
    labels: ['建設的なフィードバック'],
    attention: '確認推奨',
  },
  {
    id: 'c04',
    platform: 'youtube',
    text: 'こんにちは！',
    displayBody: '「こんにちは！」ほか同じ挨拶 3件',
    timestamp: BASE_TIME + 28_000,
    atSeconds: 28,
    author: { id: 'u04', name: 'ふうか' },
    labels: ['重複', '対応不要'],
    attention: '通常',
    repeatCount: 3,
  },
  {
    id: 'c05',
    platform: 'youtube',
    text: '何のソフトを使っているのか私も知りたいです',
    timestamp: BASE_TIME + 36_000,
    atSeconds: 36,
    author: { id: 'u05', name: 'nori' },
    labels: ['質問', '重複', '返信候補'],
    attention: '優先',
  },
  {
    id: 'c06',
    platform: 'twitch',
    text: 'つまらない、消えろ',
    displayBody: '攻撃的な表現を含むコメント（本文は抑制表示）',
    timestamp: BASE_TIME + 43_000,
    atSeconds: 43,
    author: { id: 'u06', name: 'viewer_404' },
    labels: ['要注意', '対応不要'],
    attention: '安全性注意',
  },
  {
    id: 'c07',
    platform: 'youtube',
    text: '配信者はバカだ、つまらない',
    displayBody: '攻撃的な表現を含むコメント（本文は抑制表示）',
    timestamp: BASE_TIME + 47_000,
    atSeconds: 47,
    author: { id: 'u06', name: 'viewer_404' },
    labels: ['要注意', '対応不要'],
    attention: '安全性注意',
  },
  {
    id: 'c08',
    platform: 'youtube',
    text: '手描きのトランジションすごく好き！',
    timestamp: BASE_TIME + 57_000,
    atSeconds: 57,
    author: { id: 'u08', name: 'sora' },
    labels: ['注目'],
    attention: '確認推奨',
  },
  {
    id: 'c09',
    platform: 'twitch',
    text: '今のトランジション良いですね！',
    timestamp: BASE_TIME + 62_000,
    atSeconds: 62,
    author: { id: 'u09', name: 'Leo' },
    labels: ['注目'],
    attention: '確認推奨',
  },
  {
    id: 'c10',
    platform: 'youtube',
    text: '制作ソフトの名前をもう一度教えてください',
    timestamp: BASE_TIME + 71_000,
    atSeconds: 71,
    author: { id: 'u10', name: 'リコ' },
    labels: ['質問', '重複', '返信候補'],
    attention: '優先',
  },
  {
    id: 'c11',
    platform: 'youtube',
    text: '説明が少し速いので、もう少しゆっくりだと助かります',
    timestamp: BASE_TIME + 80_000,
    atSeconds: 80,
    author: { id: 'u11', name: 'haru' },
    labels: ['建設的なフィードバック'],
    attention: '確認推奨',
  },
  {
    id: 'c12',
    platform: 'twitch',
    text: '素材を商用配信で使うときのライセンス条件は？',
    timestamp: BASE_TIME + 91_000,
    atSeconds: 91,
    author: { id: 'u12', name: 'nanami' },
    labels: ['質問', '返信候補'],
    attention: '優先',
  },
  {
    id: 'c13',
    platform: 'youtube',
    text: '今のブラシ設定も見てみたいです',
    timestamp: BASE_TIME + 99_000,
    atSeconds: 99,
    author: { id: 'u13', name: 'タク' },
    labels: ['質問'],
    attention: '確認推奨',
    simulateAnalysisError: true,
  },
  {
    id: 'c14',
    platform: 'youtube',
    text: '次回は配色の決め方も詳しく聞きたい！',
    timestamp: BASE_TIME + 108_000,
    atSeconds: 108,
    author: { id: 'u14', name: 'mai' },
    labels: ['注目', '質問'],
    attention: '確認推奨',
  },
  {
    id: 'c15',
    platform: 'twitch',
    text: '落ち着いた画面で見やすいです',
    timestamp: BASE_TIME + 119_000,
    atSeconds: 119,
    author: { id: 'u15', name: 'chika' },
    labels: ['対応不要'],
    attention: '通常',
  },
  {
    id: 'c16',
    platform: 'youtube',
    text: '完成が楽しみです、作業がんばって！',
    timestamp: BASE_TIME + 130_000,
    atSeconds: 130,
    author: { id: 'u16', name: 'yui' },
    labels: ['注目'],
    attention: '通常',
  },
] as const;

export const formatElapsed = (seconds: number) => {
  const minutes = Math.floor(seconds / 60)
    .toString()
    .padStart(2, '0');
  const remaining = (seconds % 60).toString().padStart(2, '0');
  return `${minutes}:${remaining}`;
};
