export type VoiceEngineType =
  | 'voicevox'
  | 'voicepeak'
  | 'openai'
  | 'xai'
  | 'unrealSpeech'
  | 'elevenLabs'
  | 'inworld'
  | 'gradium'
  | 'geminiTts'
  | 'openaiCompatible'
  | 'aivisSpeech'
  | 'aivisCloud'
  | 'minimax'
  | 'piperPlus'
  | 'webSpeech'
  | 'none';
